### ISSUE TITLE
All Team Members Duplication

### ISSUE THREAD

**Issue by joshuag65** [space-pirate-productions/chapmancommunities#25]
https://chapmancommunities.spacepirateproductions.com/our-team/

**Comment by space-pirate-productions** [comment]
@joshuag65 can you give me a little more detail on this one?  I've gone over the page a couple times and I'm not seeing the issue?

**Comment by joshuag65** [comment]
Team members with longer titles appear higher than those who have shorter titles. Micki Gibbs Is a Michigan leader and a national support team member. Is there a way around having her duplicated on the all team members column or do I just need to remove her from one? 

![Duplicate - Off axis](https://user-images.githubusercontent.com/113468583/190494990-8a36b35e-594b-4383-ad21-d5549ee9e877.png)
![off axis](https://user-images.githubusercontent.com/113468583/190494992-a1bc6586-423e-47e2-b84a-6771276464a4.png)

**Comment by space-pirate-productions** [comment]
@joshuag65 the title alignment issue from #24 I definitely saw and the fix should be live on the site already.  The "Micki Gibbs duplication" is the issue I wasn't seeing.  It looks like the current solution (on the live site) was just to only include her in one location.  

I may possibly have another solution if I can get it to work.  Since each "team member" is an array of image/name/title I may be able to filter out any duplicate names and then append the title from the "duplicate" to the original with a " & ".  **_This assumes you never have two different people with the same name working for you though or else the second person won't show up on the "all team members" page._**

Let me know if you wan't to go with the solution from live (removing her from one of the groups) or if you want me to try the alternate idea.

**Comment by joshuag65** [comment]
We have two employees named Josh.

**Comment by space-pirate-productions** [comment]
@joshuag65 I believe I have figured out a solution for this.  Per my previous comment, on the "all locations" tab it would remove the second occurrence for any person with the same name and combine the title from the first and second occurrence with an `&`.

This would only affect entries with the **EXACT** same first and last name spelled the same way.  So it would not affect two different team members named Josh Smith and Josh Adams, Josh Gale and Joshua Gale, or Stephen Parker and Steven Parker for example. 

Below is a screenshot of what the final result would look like on the ''all locations" tab with the other tabs the person appears on being the same as before.  Let me know if this solution works for you and I'll get it merged in and update the site with it.

![Our-Team-Chapman-Foundation-for-Caring-Communities](https://user-images.githubusercontent.com/110199482/192634297-29fc34b5-8e68-48c4-a24c-92e78291cf05.jpeg)

**Comment by joshuag65** [comment]
Looks great. Run with it. Thanks

**Comment by space-pirate-productions** [comment]
@joshuag65 change has been pushed to the dev site.
