### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by joshuag65** [space-pirate-productions/chapmancommunities#27]
Is there a to get the testimonials to auto cycle from one to the next? 

https://chapmancommunities.spacepirateproductions.com/learn/

https://chapmancommunities.spacepirateproductions.com/partner/

**Comment by space-pirate-productions** [comment]
@joshuag65 I've updated the testimonial sliders so that they will autoplay.  The library I'm using for them allows for a progress bar looks/works really good (in my opinion) and personally I like the visual indication that the slide is going to change and when but if you're not a fan let me know and I can remove it.  I can also adjust the timing if needed.
